[workspace]
members = ["crates/brightfield-spec", "crates/brightfield-conformance", "crates/brightfield-sql", "crates/brightfield-engine", "crates/brightfield-render", "crates/brightfield-ui"]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.80"
license = "MIT OR Apache-2.0"
repository = "https://github.com/meridian-online/brightfield"

[workspace.lints.rust]
unused_must_use = "warn"
missing_docs = "allow"

[workspace.lints.clippy]
pedantic = { level = "allow", priority = -1 }
