//! **The number format brightfield reads prints what d3-format prints.**
//!
//! A Mosaic spec's `xTickFormat` / `yTickFormat` is a d3-format specifier, and
//! d3-format is the authority for what one prints. `d3_format_vectors/table.rs`
//! holds what the real d3-format 3.1.2 and d3-scale 4.0.2 print for a spread of
//! specifiers and values, generated by `d3_format_vectors/gen-vectors.mjs`, and
//! these tests hold the Rust port to it, string for string.
//!
//! The values are chosen for where a port goes wrong rather than where it is
//! easy: exact ties (`2.5`, `.1s` of `2500`), which JavaScript rounds up and
//! Rust rounds to even; zero and negative zero; a negative that rounds to zero;
//! the smallest and largest exponents; a value past 1e21; `NaN`; every flag of
//! the grammar; and the unknown type, which d3-format treats as `.12~g`.

use brightfield_spec::number_format::NumberFormat;

#[path = "d3_format_vectors/table.rs"]
mod table;

/// Every `(specifier, value)` the table holds prints as d3-format prints it.
/// Mismatches are collected so a failure names every one, not the first.
#[test]
fn format_prints_what_d3_format_prints() {
    let mut wrong = Vec::new();
    for (spec, value, expected) in table::FORMAT_VECTORS {
        let Some(format) = NumberFormat::parse(spec) else {
            wrong.push(format!("`{spec}` did not parse"));
            continue;
        };
        let got = format.format(*value);
        if got != *expected {
            wrong.push(format!(
                "format({spec:?})({value:?}) = {got:?}, d3-format prints {expected:?}"
            ));
        }
    }
    assert!(
        table::FORMAT_VECTORS.len() > 500,
        "the table shrank to {} rows; a vector test over a table that is empty proves nothing",
        table::FORMAT_VECTORS.len()
    );
    assert!(
        wrong.is_empty(),
        "{} of {} vectors differ:\n{}",
        wrong.len(),
        table::FORMAT_VECTORS.len(),
        wrong.join("\n")
    );
}

/// Every axis in the table gets the tick text d3-scale's `tickFormat` gives it:
/// the precision follows the step between ticks, and an SI axis shares one
/// prefix. The step is the one d3 drew its own ticks at, so what is compared is
/// the inference from a step, which is the part that is the port's own.
#[test]
fn tick_text_is_what_d3_scale_tick_format_gives() {
    let mut wrong = Vec::new();
    for (spec, start, stop, step, values, expected) in table::TICK_VECTORS {
        let Some(format) = NumberFormat::parse(spec) else {
            wrong.push(format!("`{spec}` did not parse"));
            continue;
        };
        let ticks = format.tick_format(*start, *stop, *step);
        let got: Vec<String> = values.iter().map(|v| ticks.format(*v)).collect();
        if got != *expected {
            wrong.push(format!(
                "tickFormat({spec:?}) over [{start}, {stop}] by {step} = {got:?}, d3-scale gives {expected:?}"
            ));
        }
    }
    assert!(
        table::TICK_VECTORS.len() > 100,
        "the table shrank to {} axes",
        table::TICK_VECTORS.len()
    );
    assert!(
        wrong.is_empty(),
        "{} of {} axes differ:\n{}",
        wrong.len(),
        table::TICK_VECTORS.len(),
        wrong.join("\n")
    );
}

/// The card's own figures, read straight off the table rather than restated:
/// the axis under `s` from 0 to 2000 and under `%` from 0 to 1 are in it, so a
/// reader who doubts a figure in the card can see which d3 line it came from.
#[test]
fn the_tick_text_the_card_names_is_in_the_table() {
    let text = |spec: &str, start: f64, stop: f64| -> Vec<&'static str> {
        table::TICK_VECTORS
            .iter()
            .find(|(s, a, b, ..)| *s == spec && *a == start && *b == stop)
            .unwrap_or_else(|| panic!("no `{spec}` axis over [{start}, {stop}] in the table"))
            .5
            .to_vec()
    };
    assert_eq!(
        text("s", 0.0, 2000.0),
        ["0.0k", "0.5k", "1.0k", "1.5k", "2.0k"]
    );
    assert_eq!(
        text("%", 0.0, 1.0),
        ["0%", "20%", "40%", "60%", "80%", "100%"]
    );
}
