//! Generate `SCHEMA_AXIS_ATTRIBUTES` from the vendored Mosaic schema.
//!
//! The parser names an axis attribute a plot sets and brightfield does not
//! read, and which names are axis attributes at all is Mosaic's to say. So the
//! list is read from Mosaic's published schema, vendored in
//! `vendor/mosaic-schema/`, at build time: an edit to that file reruns this
//! script and changes the list, and the schema itself is never compiled into
//! the binary. `vendor/mosaic-schema/README.md` names where the file came from.

use std::path::PathBuf;

#[path = "src/axis_vocabulary/schema.rs"]
mod schema;

/// The vendored schema, relative to this crate's manifest directory.
const SCHEMA_PATH: &str = "vendor/mosaic-schema/v0.24.2.json";

fn main() {
    println!("cargo:rerun-if-changed={SCHEMA_PATH}");
    println!("cargo:rerun-if-changed=src/axis_vocabulary/schema.rs");

    let manifest_dir = PathBuf::from(
        std::env::var_os("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR"),
    );
    let path = manifest_dir.join(SCHEMA_PATH);
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read the vendored Mosaic schema at {}: {e}", path.display()));
    let document: serde_json::Value = serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("{} is not JSON: {e}", path.display()));
    let names = schema::schema_axis_attribute_names(&document)
        .unwrap_or_else(|e| panic!("{}: {e}", path.display()));

    let mut out = String::new();
    out.push_str(
        "/// The axis attribute names Mosaic's schema declares on a plot, sorted.\n\
         /// Generated by `build.rs` from `",
    );
    out.push_str(SCHEMA_PATH);
    out.push_str("`.\npub const SCHEMA_AXIS_ATTRIBUTES: &[&str] = &[\n");
    for name in &names {
        out.push_str("    \"");
        out.push_str(name);
        out.push_str("\",\n");
    }
    out.push_str("];\n");

    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("cargo sets OUT_DIR"));
    std::fs::write(out_dir.join("schema_axis_attributes.rs"), out)
        .expect("write the generated axis attribute list");
}
