// Generates table.rs, the reference vectors for brightfield's d3-time-format port,
// from the real d3-time-format 4.1.0 (with d3-time 3.1.0):
//
//   npm install d3-time-format@4.1.0
//   TZ=America/Los_Angeles node gen-vectors.mjs > table.rs
//
// The Rust tests in ../d3_time_format_vectors.rs read table.rs; nothing else does.
//
// `utcFormat` prints in UTC whatever the machine's zone is, and the script runs
// under a zone that is not UTC so that a table generated with `timeFormat` by
// mistake would differ from the port on every row.
import { utcFormat } from "d3-time-format";

const str = (s) => JSON.stringify(s);

// Instants as ISO text, so a year below 1000 is written as it is. Each is chosen
// for where a calendar port goes wrong: the epoch and the millisecond before it,
// a leap day, the last instant of a year that is week 1 of the next, a Sunday and
// a Friday that are still in the previous year's last ISO week, a Monday that is
// already in the next year's first, the hours either side of noon and midnight, a
// year that is not four digits wide, and one past the millennium.
const INSTANTS = [
  "1970-01-01T00:00:00.000Z",
  "1969-12-31T23:59:59.999Z",
  "2024-03-01T00:00:00.000Z",
  "2024-02-29T12:34:56.789Z",
  "2024-12-31T23:59:59.999Z",
  "2021-01-03T08:00:00.000Z",
  "2021-01-01T00:00:00.000Z",
  "2018-12-31T00:00:00.000Z",
  "2016-01-01T13:45:00.000Z",
  "2020-12-31T23:00:00.000Z",
  "2026-09-30T14:05:00.000Z",
  "2000-01-01T00:00:00.000Z",
  "1900-03-01T00:00:00.000Z",
  "0999-12-31T00:00:00.000Z",
  "2024-06-15T12:00:00.000Z",
  "2024-06-15T00:30:00.000Z",
  "2024-06-15T23:59:59.000Z",
  "2999-12-31T18:00:00.000Z",
];

// The directives d3-time-format reads, each alone.
const DIRECTIVES = "aAbBcdefgGHIjLmMpqQsSuUVwWxXyYZ%";
// The padding modifiers apply to the directives that print a padded number.
const PADDED = "deHIjLmMSUVWyYgG";

const SPECS = [];
for (const d of DIRECTIVES) SPECS.push(`%${d}`);
for (const m of ["-", "_", "0"]) for (const d of PADDED) SPECS.push(`%${m}${d}`);
SPECS.push(
  "%Y-%m-%d",
  "%B %Y",
  "%H:%M",
  "%I:%M %p",
  "%b %-d, %Y",
  "%Y-%m-%dT%H:%M:%S.%LZ",
  "%_d/%_m",
  "%a %e %b",
  "%Y-W%V-%u",
  "plain text and %Y",
);

const out = [];
out.push("// @generated by gen-vectors.mjs from d3-time-format 4.1.0 (d3-time 3.1.0) — do not edit by hand.");
out.push("/// `(specifier, milliseconds since the epoch, what utcFormat prints)`.");
out.push("pub const DATE_VECTORS: &[(&str, i64, &str)] = &[");
for (const spec of SPECS) {
  const f = utcFormat(spec);
  for (const iso of INSTANTS) {
    const ms = Date.parse(iso);
    out.push(`    (${str(spec)}, ${ms}, ${str(f(new Date(ms)))}),`);
  }
}
out.push("];");
console.log(out.join("\n"));
