// Generates table.rs, the reference vectors for brightfield's d3-format port,
// from the real d3-format 3.1.2, d3-scale 4.0.2 and d3-array 3.2.4:
//
//   npm install d3-format@3.1.2 d3-scale@4.0.2 d3-array@3.2.4
//   node gen-vectors.mjs > table.rs
//
// The Rust tests in ../d3_format_vectors.rs read table.rs; nothing else does.
import { format } from "d3-format";
import { tickFormat } from "d3-scale";
import { tickStep, ticks } from "d3-array";

const lit = (v) => {
  if (Number.isNaN(v)) return "f64::NAN";
  if (v === Infinity) return "f64::INFINITY";
  if (v === -Infinity) return "f64::NEG_INFINITY";
  if (Object.is(v, -0)) return "-0.0";
  let s = String(v);
  if (!/[.e]/.test(s)) s += ".0";
  return s;
};
const str = (s) => JSON.stringify(s);

const SPECS = [
  ".2s", ".1s", "s", "~s", ".0f", ".1f", ".0%", "%", "+.1f", "+f", ".2f", ",.2f", ",d", "d", "$,.2f", "(,.2f", ".2e", ".3g", ".3r",
  ".1p", "x", "b", "#x", "08.2f", ">10.1f", "<10,d", "^10d", "n", "", "q", "010,d",
];
const VALUES = [
  0, -0, 0.5, 1.5, 2.5, 0.125, 1250, 1500, 2500, 2000000, 0.001, 123456789, -1500, 999.9999,
  0.30000000000000004, 1e-7, 1e21, NaN,
];

const out = [];
out.push("// @generated by gen-vectors.mjs from d3-format 3.1.2, d3-scale 4.0.2 — do not edit by hand.");
out.push("pub const FORMAT_VECTORS: &[(&str, f64, &str)] = &[");
for (const spec of SPECS) {
  const f = format(spec);
  for (const v of VALUES) {
    out.push(`    (${str(spec)}, ${lit(v)}, ${str(f(v))}),`);
  }
}
out.push("];");
out.push("");

// tickFormat(count, spec) on a linear scale — d3-scale 4.0.2 — for specs
// where it and d3.format agree on the treatment of a precision.
const TICK_SPECS = ["s", "~s", "%", "+f", "f", ",f", "d", "g", "", "r", "p", "e", ".1%", "+.1f", ",.0f"];
const DOMAINS = [
  [0, 2000, 5], [0, 1, 5], [0, 2e6, 5], [-1, 1, 5], [0, 100, 5], [0.001, 0.005, 5], [1000, 2000, 10], [-50, 50, 5],
  [0, 0.1, 5], [0, 25000, 5],
];
out.push("/// `(specifier, domain start, domain stop, step, tick values, tick text)`.");
out.push("pub type TickVector = (&'static str, f64, f64, f64, &'static [f64], &'static [&'static str]);");
out.push("");
out.push("pub const TICK_VECTORS: &[TickVector] = &[");
for (const spec of TICK_SPECS) {
  for (const [a, b, count] of DOMAINS) {
    const step = tickStep(a, b, count);
    const t = ticks(a, b, count);
    const fmt = tickFormat(a, b, count, spec);
    out.push(
      `    (${str(spec)}, ${lit(a)}, ${lit(b)}, ${lit(step)}, &[${t.map(lit).join(", ")}], &[${t.map((v) => str(fmt(v))).join(", ")}]),`,
    );
  }
}
out.push("];");
console.log(out.join("\n"));
